djangodelights/djangodelights/urls.py
from django.conf import settings # new
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static # new


urlpatterns = [
    path("", include("inventory.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangodelights/inventory/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # home/
    path("", views.home, name="home"),

    # account/
    path("account/", include("django.contrib.auth.urls")),
    path("account/signup/", views.SignUp.as_view(), name="signup"),

    # menu/
    path("menu/", views.MenuItemList.as_view(), name="menuitem_list"),
    path("menu/new/", views.MenuItemCreateView.as_view(), name="menuitem_add"),
    path("menu/update/<int:pk>", views.MenuItemUpdateView.as_view(), name="menuitem_update"),

    # menu/<menuitem_title>/recipe/
    path("menu/<menuitem_title>/recipe/", views.RecipeRequirementList.as_view(), name="recipe_list"),
    path("menu/<menuitem_title>/recipe/new/", views.RecipeRequirementCreateView.as_view(), name="recipe_add"),
    path("menu/<menuitem_title>/recipe/update/<int:pk>", views.RecipeRequirementUpdateView.as_view(), name="recipe_update"),
    path("menu/<menuitem_title>/recipe/delete/<int:pk>", views.RecipeRequirementDeleteView.as_view(), name="recipe_delete"),

    # ingredient/
    path("ingredient/", views.IngredientList.as_view(), name="ingredient_list"),
    path("ingredient/new/", views.IngredientCreateView.as_view(), name="ingredient_add"),
    path("ingredient/update/<int:pk>", views.IngredientUpdateView.as_view(), name="ingredient_update"),

    # purchase/
    path("purchase/", views.PurchaseList.as_view(), name="purchase_list"),
    path("purchase/new/", views.PurchaseCreateView.as_view(), name="purchase_add"),

    # report/
    path("report/", views.ReportView.as_view(), name="report"),
    
]

djangodelights/inventory/models.py
from django.db import models
from django.urls import reverse

units_per_gram = {"grams": 1, "kilograms": 1000, "pounds": 453.592, "ounce": 28.35}

def convert_to_grams(quantity: float, unit: str):
    return quantity * units_per_gram[unit]


# --------------------------------- MENU ITEM ---------------------------------

class MenuItem(models.Model):
    """
    Represents an entry off the restaurant's menu
    """
    title = models.CharField(max_length=200, unique=True)
    price = models.FloatField(default=0.00)
    image = models.ImageField(blank=True, null=True, upload_to="menuitem_images/")

    def get_absolute_url(self):
        return "/menu"
    
    def available(self):
        return all(X.enough() for X in self.reciperequirement_set.all())

    def __str__(self):
        return f"title={self.title}; price={self.price}"

    def save(self, *args, **kwargs):
        self.title = self.title.lower()
        return super(MenuItem, self).save(*args, **kwargs)


# -------------------------------- INGREDENT ----------------------------------

class Ingredient(models.Model):
    """
    Represents a single ingredient in the restaurant's inventory
    """
    name = models.CharField(max_length=200, unique=True)
    quantity = models.FloatField(default=0)

    GRAM = "grams"
    KILOGRAM = "kilograms"
    POUND = "pounds"
    OUNCE = "ounces"
    COUNT = "counts"
    UNITS_CHOICES = {
        (GRAM, "gram"),
        (KILOGRAM, "kilogram"),
        (POUND, "pound"),
        (OUNCE, "ounce"),
        (COUNT, "count"),
    }
    unit = models.CharField(max_length=10,choices=UNITS_CHOICES, default=GRAM)

    price_per_unit = models.FloatField(default=0)

    def get_absolute_url(self):
        return "/ingredient"

    def __str__(self):
        return f"""
        name={self.name};
        qty={self.quantity};
        unit={self.unit};
        unit_price={self.price_per_unit}
        """
    
    def save(self, *args, **kwargs):
        self.name = self.name.lower()
       
        return super(Ingredient, self).save(*args, **kwargs)


# --------------------------- RECIPE REQURIEMENT ------------------------------

class RecipeRequirement(models.Model):
    """
    Represents an ingredient required for a recipe for a MenuItem
    """
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField(default=0)

    def __str__(self):
        return f"menu_item=[{self.menu_item.__str__()}]; ingredient={self.ingredient.name}; qty={self.quantity}"

    def enough(self):
        return self.quantity <= self.ingredient.quantity

    def get_absolute_url(self):
        return reverse("recipe_list", kwargs={"menuitem_title": self.menu_item.title.replace(" ", "-")})
    


# --------------------------------- PURCHASE ---------------------------------

class Purchase(models.Model):
    """
    Represents a purchase of a MenuItem
    """
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"menu_item=[{self.menu_item.__str__()}]; time={self.timestamp}"

    def get_absolute_url(self):
        return "/purchase"

djangodelights/inventory/forms.py
from django import forms
from .models import MenuItem, Ingredient, RecipeRequirement, Purchase


# ----------------------- MENU ITEM -------------------------

class MenuItemForm(forms.ModelForm):

    class Meta:
        model = MenuItem
        fields = "__all__"


# ----------------------- INGREDENT -------------------------

class IngredientForm(forms.ModelForm):

    class Meta:
        model = Ingredient
        fields = "__all__"


# ------------------- RECIPE REQURIEMENT --------------------

class RecipeRequirementForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        initial = kwargs["initial"]
        super(RecipeRequirementForm, self).__init__(*args, **kwargs)
        menu_item = initial["menu_item"]
        self.fields['menu_item'].queryset = MenuItem.objects.filter(title=menu_item.title)

    class Meta:
        model = RecipeRequirement
        fields = "__all__"


# ----------------------- PURCHASE --------------------------

class PurchaseForm(forms.ModelForm):

    class Meta:
        model = Purchase
        fields = "__all__"

djangodelights/inventory/views.py
from django.db.models import query, Sum
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import MenuItem, Ingredient, RecipeRequirement, Purchase
from .forms import MenuItemForm, IngredientForm, RecipeRequirementForm, PurchaseForm

# --------------------------------- HOME -----------------------------------

def home(request):
    context = {}
    return render(request, "inventory/home.html", context)


# --------------------------------- SIGNUP -----------------------------------


class SignUp(CreateView):
    form_class = UserCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("login")


# --------------------------------- LOGOUT -----------------------------------

def logout_view(request):
    logout(request)


# --------------------------------- MENU ITEM ---------------------------------

class MenuItemList(LoginRequiredMixin, ListView):
    model = MenuItem


class MenuItemCreateView(LoginRequiredMixin, CreateView):
    model = MenuItem
    form_class = MenuItemForm
    template_name = "inventory/menuitem_add_form.html"


class MenuItemUpdateView(LoginRequiredMixin, UpdateView):
    model = MenuItem
    form_class = MenuItemForm
    template_name = "inventory/menuitem_update_form.html"


# -------------------------------- INGREDENT ----------------------------------

class IngredientList(LoginRequiredMixin, ListView):
    model = Ingredient


class IngredientCreateView(LoginRequiredMixin, CreateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = "inventory/ingredient_add_form.html"


class IngredientUpdateView(LoginRequiredMixin, UpdateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = "inventory/ingredient_update_form.html"



# --------------------------- RECIPE REQURIEMENT ------------------------------

class RecipeRequirementList(LoginRequiredMixin, ListView):
    model = RecipeRequirement
    template_name = "inventory/recipe_list.html"

    def get_queryset(self):
        menuitem_title = self.kwargs["menuitem_title"].replace("-", " ")
        menuitem = MenuItem.objects.get(title=menuitem_title)
        queryset = menuitem.reciperequirement_set.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        menuitem_title = self.kwargs["menuitem_title"].replace("-", " ")
        menuitem = MenuItem.objects.get(title=menuitem_title)
        context["menuitem"] = menuitem
        return context


class RecipeRequirementCreateView(LoginRequiredMixin, CreateView):
    model = RecipeRequirement
    form_class = RecipeRequirementForm
    template_name = "inventory/recipe_add_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        menuitem_title = self.kwargs["menuitem_title"].replace("-", " ")
        menuitem = MenuItem.objects.get(title=menuitem_title)
        context["menuitem"] = menuitem
        return context
    
    def get_initial(self):
        initial = super().get_initial()
        menuitem_title = self.kwargs["menuitem_title"].replace("-", " ")
        initial["menu_item"] = MenuItem.objects.get(title=menuitem_title)
        return initial

class RecipeRequirementUpdateView(LoginRequiredMixin, UpdateView):
    model = RecipeRequirement
    form_class = RecipeRequirementForm
    template_name = "inventory/recipe_update_form.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        menuitem_title = self.kwargs["menuitem_title"].replace("-", " ")
        menuitem = MenuItem.objects.get(title=menuitem_title)
        context["menuitem"] = menuitem
        return context

    def get_initial(self):
        initial = super().get_initial()
        menuitem_title = self.kwargs["menuitem_title"].replace("-", " ")
        initial["menu_item"]  = MenuItem.objects.get(title=menuitem_title)
        return initial


class RecipeRequirementDeleteView(LoginRequiredMixin, DeleteView):
    model = RecipeRequirement
    form_class = RecipeRequirementForm
    template_name = "inventory/recipe_delete_form.html"

    def get_success_url(self):
        menuitem_title = self.kwargs["menuitem_title"]
        return reverse("recipe_list", kwargs={"menuitem_title": menuitem_title})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        menuitem_title = self.kwargs["menuitem_title"].replace("-", " ")
        menuitem = MenuItem.objects.get(title=menuitem_title)
        context["menuitem"] = menuitem
        return context


# --------------------------------- PURCHASE ---------------------------------

class PurchaseList(LoginRequiredMixin, ListView):
    model = Purchase
    template_name = "inventory/purchase_list.html"


class PurchaseCreateView(LoginRequiredMixin, CreateView):
    model = Purchase
    form_class = PurchaseForm
    template_name = "inventory/purchase_add_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        available_menuitems = [X for X in MenuItem.objects.all() if X.available()]
        context["available_menuitems"] = available_menuitems
        return context

    def post(self, request, *args, **kwargs):

        menu_item_id = request.POST["menu_item"]
        menu_item = MenuItem.objects.get(pk=menu_item_id)
        
        for required_recipe in menu_item.reciperequirement_set.all():
            ingredient_in_stock = required_recipe.ingredient
            ingredient_in_stock.quantity -= required_recipe.quantity
            ingredient_in_stock.save()

        return super().post(request, *args, **kwargs)


# ----------------------------------- REPORT ---------------------------------

class ReportView(LoginRequiredMixin, TemplateView):
    template_name = "inventory/report.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        purchases = Purchase.objects.all()

        revenue = purchases.aggregate(Sum("menu_item__price"))['menu_item__price__sum']

        if revenue == None:
            revenue = 0

        total_cost = 0

        for purchase in purchases:
            for recipe in purchase.menu_item.reciperequirement_set.all():
                required_quantity = recipe.quantity
                price_per_unit = recipe.ingredient.price_per_unit
                total_cost += required_quantity * price_per_unit

        profit = revenue - total_cost

        context["revenue"] = revenue
        context["total_cost"] = total_cost
        context["profit"] = profit

        return context

djangodelights/inventory/templates/inventory/base.html
<!DOCTYPE html>
{% load static %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'inventory/base.css' %}">
    <script src="{% static 'inventory/app.js' %}"></script> 
    <title>Django Delight Restaurant</title>
</head>

<body class="body">
    <div class="header">
        <div>
            <a href="{% url 'home' %}"><img class="home-icon" src="{% static 'inventory/home-icon.png' %}" alt="Home" /></a>

            {% if user.username %}
                Welcome {{ user.username }} :) <a class="button" href="{% url 'logout' %}">Logout</a>
                
            {% else %}
                <a class="button" href="{% url 'login' %}">Login</a> 
                <a class="button" href="{% url 'signup' %}">Register</a>
            {% endif %}
        </div>

        <h1>Django Delight</h1>
        <p>Restaurant</p>
    </div>

    {% block content %}
    {% endblock content %}

</body>

djangodelights/inventory/templates/inventory/home.html
{% extends "inventory/base.html"%}

{% block head %}
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<body>
    <div class="menu-bar">
        <a href="{% url 'menuitem_list' %}">Menu</a>
        <a href="{% url 'ingredient_list' %}">Ingredient</a>
        <a href="{% url 'purchase_list' %}">Purchase</a>
        <a href="{% url 'report' %}">Report</a>
    </div>
</body>

<div class="subcontent">
{% block subcontent %}
{% endblock subcontent %}
</div>

{% endif %}

{% endblock content %}

djangodelights/inventory/templates/inventory/ingredient_add_form.html
{% extends "inventory/home.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="ingredient-add">

    <h3>Add New Ingredient Item</h3>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button submit-button" type="submit" value="Add">
    </form>

</div>
{% endblock subcontent %}

djangodelights/inventory/templates/inventory/ingredient_list.html
{% extends "inventory/home.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="ingredient-list">

    <div class="sub-header">
        <h3>Ingredients</h3>
        <a class="button add-button" href="{% url 'ingredient_add' %}">Add Ingredient</a>
    </div>

    {% if ingredient_list|length == 0 %}
        <p>No ingredient listed yet</p>
    {% endif %}

    <ul class="list">
        {% for ingredient in ingredient_list|dictsort:"name" %}
            <li>{{ ingredient.name|title }}
                {{ ingredient.quantity }} {{ ingredient.unit }}
                <a href="{% url 'ingredient_update' ingredient.id %}">Edit</a>
            </li>
        {% endfor %}
    </ul>

</div>
{% endblock subcontent %}

djangodelights/inventory/templates/inventory/menu.html
{% extends "inventory/base.html"%}

{% block head %}
{% endblock %}

{% block content %}

    <p>This is menu.html</p>

    <div class="menu-menu-bar">
        <ul>
            <a href="{% url 'menuitem_list' %}"><li>Menu</li></a>
            <a href="{% url 'ingredient_list' %}"><li>Ingredient</li></a>
            <a href="{% url 'report_list' %}"><li>Report</li></a>
        </ul>
    </div>

    {% block subcontent %}
    {% endblock subcontent %}

{% endblock %}

djangodelights/inventory/templates/inventory/menuitem_add_form.html
{% extends "inventory/home.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="menuitem-add">

    <h3>Add New Menu Item</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button submit-button" type="submit" value="Add">
    </form>

</div>
{% endblock subcontent %}

djangodelights/inventory/templates/inventory/menuitem_list.html
{% extends "inventory/home.html"%}
{% load static %}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="menuitem-list">

    <div class="sub-header">
        <h3>Menu</h3>
        <a class="button add-button" href="{% url 'menuitem_add' %}">Add Menu</a>
    </div>

    <div class="gallery">
        {% if menuitem_list|length == 0 %}
            <p>No menu listed yet</p>
        {% endif %}

        {% for menuitem in menuitem_list|dictsort:"title" %}
            <div class="item">

                {% if menuitem.image %}
                    <img class="imagein" src="{{ menuitem.image.url }}" alt="{{ menuitem.title }}" />
                {% else %}
                    <p class="imagein">no image</p>
                {% endif %}
    
                {% comment %} <a href="{% url 'recipe_list' menuitem.title|slugify %}"><img class="imageout" src="{% static 'inventory/view-recipe-image.png' %}" alt="view-recipe-image" /></a> {% endcomment %}
                <div class="overlay">
                    <a class="view-image" href="{% url 'recipe_list' menuitem.title|slugify %}">View Recipe</a>
                </div>

                <div class="menutitle">
                    {{ menuitem.title|title }}
                    ${{ menuitem.price|floatformat:2 }}
                    <a href="{% url 'menuitem_update' menuitem.id %}">Edit</a>
                </div>

            </div>
        {% endfor %}
    </div>

</div> 
{% endblock subcontent %}

djangodelights/inventory/templates/inventory/menuitem_update_form.html
{% extends "inventory/home.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="menuitem-update">

    <h3>Update Menu</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button update-button" type="submit" value="Update">
    </form>

</div>
{% endblock subcontent %}

djangodelights/inventory/templates/inventory/purchase_add_form.html
{% extends "inventory/home.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="purchase-add">

    <h3>Purchase Menu Item</h3>

    <form method="POST">
        {% csrf_token %}
        <p>
            <label for="menu_item">Menu item:</label>
            <select name="menu_item" id="menu_item" required>
                <option value selected>-----</option>
            {% for menu_item in available_menuitems %}
                <option value={{ menu_item.id }}>{{ menu_item.title }}</option>
            {% endfor %}
            </select>
        </p>
        <input class="button submit-button" type="submit" value="Add">
    </form>

</div>
{% endblock subcontent %}

djangodelights/inventory/templates/inventory/purchase_list.html
{% extends "inventory/home.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="purchase-list">

    <div class="sub-header">
        <h3>Purchases</h3>  
        <a class="button add-button" href="{% url 'purchase_add' %}">Add Purchase</a>
    </div>

    {% if purchase_list|length == 0 %}
        <p>No purchase listed yet</p>
    {% endif %}

    <ul class="list">
        {% for purchase in purchase_list %}
            <li>{{ purchase.menu_item.title|title }}
                <div class="timestamp">
                    {{ purchase.timestamp }}
                </div>
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock subcontent %}

djangodelights/inventory/templates/inventory/recipe_delete_form.html
{% extends "inventory/home.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="recipe-delete">

    <h3>Delete {{reciperequirement.ingredient.name|title }} from {{ menuitem.title|title }} Recipe</h3>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input id="delete_button" type="submit" value="Delete">
    </form>

</div>
{% endblock subcontent %}

djangodelights/inventory/templates/inventory/recipe_list.html
{% extends "inventory/home.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="recipe-list">

    <div class="sub-header">
        <h3>{{ menuitem.title|title }} Recipe</h3>
        <a class="button add-button" href="{% url 'recipe_add' menuitem.title|slugify %}">Add Recipe</a>
    </div>

    {% if reciperequirement_list|length == 0 %}
        <p>No recipe listed yet</p>
    {% endif %}

    <ul class="list">
        {% for recipe in reciperequirement_list|dictsort:"ingredient.name" %}
            <li>{{ recipe.ingredient.name|title }} 
                {{ recipe.quantity }}
                {{ recipe.ingredient.unit }} 

                <a href="{% url 'recipe_update' menuitem_title=menuitem.title|slugify pk=recipe.id %}">Edit</a>
            </li>
        {% endfor %}
    </ul>
    
</div>

</div>
{% endblock subcontent %}

djangodelights/inventory/templates/inventory/recipe_update_form.html
{% extends "inventory/home.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
<div class="recipe-update">

    <h3>Update {{ menuitem.title|title }} Recipe Ingredient</h3>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button update-button" type="submit" value="Update">

        <a class="button delete-button" href="{% url 'recipe_delete' menuitem_title=menuitem.title|slugify pk=reciperequirement.id %}">Delete</a>
    </form>

</div>
{% endblock subcontent %}

djangodelights/inventory/templates/inventory/report_list.html
{% extends "inventory/menu.html"%}

{% block head %}
{% endblock %}

{% block subcontent %}
    <p>This is report_list.html</p>

    <a href="{% url 'report_add' %}"><p>Add Purchase</p></a>

    <div>
        <p>Reports</p>
        <ul>
            {% for purchase in purchase_list %}
                <li>{{ purchase }} {{ purchase.id }}
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock subcontent %}